### PR TITLE
feat: add drawer menu for mobile

### PR DESCRIPTION
**Pull request by invisal**

### CODE REVIEW

**Comment by rin-yato** [comment]
I think you should put any public routes into `(public)/...` this is for grouping routes together without including public as the pathname.

**Comment by rin-yato** [comment]
Maybe you should add the sorting className for prettier? When having long className it can be hard to find what you are looking for if the className order is messy.

https://tailwindcss.com/blog/automatic-class-sorting-with-prettier

You can find the docs here, pretty easy to setup just install dev dep and add the name to prettier.config.js plugin

**Comment by invisal** [comment]
> Maybe you should add the sorting className for prettier? When having long className it can be hard to find what you are looking for if the className order is messy.
> 
> https://tailwindcss.com/blog/automatic-class-sorting-with-prettier
> 
> You can find the docs here, pretty easy to setup just install dev dep and add the name to prettier.config.js plugin
> 
> And since you disabled the eslint rule already, it shouldnt conflict anymore.

I did install it but it will not pass the hook as it requires me to prettier 22 other files.

**Comment by invisal** [comment]
> I think you should put any public routes into `(public)/...` this is for grouping routes together without including public as the pathname.

Got it.

**Review by rin-yato — APPROVED** [review]
Okay, looks good to me!🔥

**Pull request merged**
